// Generated by bf-codegen.

#include "bfni.h"

bf_bool_t hello_world(BFCalls calls, BFRuntimeEnv* env, BFRuntimeReport* report) {
// Preparation starts.
    report->file_name = __FILE__;
    report->func_name = __FUNCTION__;

    const bf_size_t TAPE_LEN = calls.tape_len(env);
    bf_byte_t* tape = calls.alloc_tape(env, TAPE_LEN);
    if (BF_NULL == tape) {
        report->error_kind = BFErrorOutOfMemory;
        return BF_FALSE;
    }
    bf_off_t pos = 0;
// Preparation ends.

// Code starts.
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 8;
L0:
    if (0 == tape[pos]) goto L1;
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 9;
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += -1;
    goto L0;
L1:
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 4;
L2:
    if (0 == tape[pos]) goto L3;
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 7;
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += -1;
    goto L2;
L3:
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 1;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    tape[pos] += 7;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    tape[pos] += 3;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    {
        bf_off_t new_pos = pos + 2;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 6;
L4:
    if (0 == tape[pos]) goto L5;
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 7;
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += -1;
    goto L4;
L5:
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 2;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    tape[pos] += -12;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 6;
L6:
    if (0 == tape[pos]) goto L7;
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 9;
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += -1;
    goto L6;
L7:
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 1;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    tape[pos] += 3;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    tape[pos] += -6;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    tape[pos] += -8;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    {
        bf_off_t new_pos = pos + 3;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 4;
L8:
    if (0 == tape[pos]) goto L9;
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 8;
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += -1;
    goto L8;
L9:
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 1;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
// Code ends.

    return BF_TRUE;
}

bf_bool_t hello(BFCalls calls, BFRuntimeEnv* env, BFRuntimeReport* report) {
// Preparation starts.
    report->file_name = __FILE__;
    report->func_name = __FUNCTION__;

    const bf_size_t TAPE_LEN = calls.tape_len(env);
    bf_byte_t* tape = calls.alloc_tape(env, TAPE_LEN);
    if (BF_NULL == tape) {
        report->error_kind = BFErrorOutOfMemory;
        return BF_FALSE;
    }
    bf_off_t pos = 0;
// Preparation ends.

// Code starts.
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 8;
L0:
    if (0 == tape[pos]) goto L1;
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 9;
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += -1;
    goto L0;
L1:
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 4;
L2:
    if (0 == tape[pos]) goto L3;
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 7;
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += -1;
    goto L2;
L3:
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 1;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    tape[pos] += 7;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    tape[pos] += 3;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    {
        bf_off_t new_pos = pos + 2;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 6;
L4:
    if (0 == tape[pos]) goto L5;
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 7;
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += -1;
    goto L4;
L5:
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 2;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    tape[pos] += -12;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 6;
L6:
    if (0 == tape[pos]) goto L7;
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 9;
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += -1;
    goto L6;
L7:
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 1;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    tape[pos] += 3;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    tape[pos] += -6;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    tape[pos] += -8;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
    {
        bf_off_t new_pos = pos + 3;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 4;
L8:
    if (0 == tape[pos]) goto L9;
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 8;
    {
        bf_off_t new_pos = pos + 1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorOverflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += -1;
    goto L8;
L9:
    {
        bf_off_t new_pos = pos + -1;
        if (new_pos >= TAPE_LEN) {
            report->error_kind = BFErrorUnderflow;
            return BF_FALSE;
        }
        pos = new_pos;
    }
    tape[pos] += 1;
    if (!calls.putchar(env, tape[pos])) {
        report->error_kind = BFErrorOutStream;
        return BF_FALSE;
    }
// Code ends.

    return BF_TRUE;
}
