use std::{collections::HashSet, fs::File, io::{self, Write}, path::Path};

use bf_ir::ir::IR;

use crate::inst_translator::InstTranslator;

pub struct CodeLine {
    indents: usize,
    content: String,
}

impl CodeLine {
    pub fn new(indents: usize, content: String) -> Self {
        Self {
            indents,
            content,
        }
    }
}

impl CodeLine {
    fn as_string(&self) -> String {
        let spaces: String = std::iter::repeat(' ').take(self.indents).collect();
        format!("{}{}", spaces, self.content)
    }
}

pub struct CodeFile {
    lines: Vec<CodeLine>,
    func_names: HashSet<String>,
}

impl CodeFile {
    pub fn new() -> Self {
        let mut lines = Vec::new();

        lines.push(CodeLine::new(
            0,
            "// Generated by bf-codegen.".into()
        ));

        lines.push(CodeLine::new(
            0,
            "".into()
        ));

        // alloca()
        lines.push(CodeLine::new(
            0,
            "#include <alloca.h>".into()
        ));

        // int8_t
        lines.push(CodeLine::new(
            0,
            "#include <stdint.h>".into()
        ));

        // getchar(), putchar(), fprintf()
        lines.push(CodeLine::new(
            0,
            "#include <stdio.h>".into()
        ));

        // exit()
        lines.push(CodeLine::new(
            0,
            "#include <stdlib.h>".into()
        ));
        
        lines.push(CodeLine::new(
            0,
            "#include <string.h>".into()
        ));
        
        lines.push(CodeLine::new(
            0,
            "".into()
        ));

        Self {
            lines,
            func_names: HashSet::new()
        }
    }
}

impl CodeFile {
    pub fn add_bf_func(&mut self, name: String, ir: IR, boundary_check: bool) -> bool {
        if self.func_names.contains(&name) {
            return false;
        }
        self.func_names.insert(name.clone());

        self.lines.push(CodeLine::new(
            0,
            format!("void {}(const size_t TAPE_LEN) {{", name)
        ));

        self.lines.push(CodeLine::new(
            4,
            "int8_t* tape = alloca(TAPE_LEN);".into()
        ));

        self.lines.push(CodeLine::new(
            4,
            "memset(tape, 0, TAPE_LEN);".into()
        ));

        self.lines.push(CodeLine::new(
            4,
            "size_t pos = 0;".into()
        ));

        self.lines.push(CodeLine::new(
            0,
            "".into()
        ));

        let it = InstTranslator::new(boundary_check);
        let mut inst_lines = it.translate(ir.instructions());
        self.lines.append(&mut inst_lines);

        self.lines.push(CodeLine::new(
            0,
            "}".into()
        ));

        self.lines.push(CodeLine::new(
            0,
            "".into()
        ));
        
        true
    }
}

impl CodeFile {
    pub fn write_to_disk(self, path: &str) -> io::Result<()> {
        let mut file = File::create(path)?;
        
        for line in self.lines {
            writeln!(file, "{}", line.as_string())?
        }

        Ok(())
    }
}
