use std::{collections::HashSet, fs::File, io::{self, Write}, path::Path};


use crate::{c_func::CFunction, inst_translator::CodeLine};

pub struct CodeFile {
    funcs: HashSet<CFunction>,
}

impl CodeFile {
    pub fn prologue() -> Vec<CodeLine> {
        let mut lines = Vec::new();

        lines.push(CodeLine::new(
            0,
            "// Generated by bf-codegen.".into()
        ));

        lines.push(CodeLine::new_empty_line());

        lines.push(CodeLine::new(
            0,
            "#include \"bfni.h\"".into()
        ));
        
        lines
    }
}

impl CodeFile {
    pub fn new() -> Self {
        Self {
            funcs: HashSet::new(),
        }
    }
}

impl CodeFile {
    pub fn add_bf_func(&mut self, func: CFunction) -> bool {
        self.funcs.insert(func)
    }
}

impl CodeFile {
    pub fn write_to_disk(self, path: &Path) -> io::Result<()> {
        let mut file = File::create(path)?;

        let mut lines = Vec::new();

        lines.append(&mut Self::prologue());
        
        for mut func in self.funcs {
            lines.push(CodeLine::new_empty_line());
            lines.append(&mut func.lines);
        }

        for line in lines {
            writeln!(&mut file, "{}", line.as_string())?;
        }

        Ok(())
    }
}

