use std::{collections::BTreeSet, io::{self, Write}};

use crate::{c_func::CFunction, inst_translator::CodeLine};

pub struct CodeFile {
    funcs: BTreeSet<CFunction>,
}

impl CodeFile {
    pub fn prologue() -> Vec<CodeLine> {
        let mut lines = Vec::new();

        lines.push(CodeLine::new(
            0,
            "// Generated by bf-codegen.".into()
        ));

        lines.push(CodeLine::new_empty_line());

        lines.push(CodeLine::new(
            0,
            "#include \"bfni.h\"".into()
        ));
        
        lines
    }
}

impl CodeFile {
    pub fn new() -> Self {
        Self {
            funcs: BTreeSet::new(),
        }
    }
}

#[derive(Debug)]
pub enum AddFuncError {
    DuplicatedFuncName(String),
}

impl CodeFile {
    pub fn add_bf_func(&mut self, func: CFunction) -> Result<(), AddFuncError> {
        let name = func.name.clone();
        
        if self.funcs.insert(func) {
            Ok(())
        } else {
            Err(AddFuncError::DuplicatedFuncName(name))
        }
    }
}

impl CodeFile {
    pub fn write_to(self, wr: &mut dyn Write) -> io::Result<()> {
        let mut lines = Vec::new();

        lines.append(&mut Self::prologue());
        
        for mut func in self.funcs {
            lines.push(CodeLine::new_empty_line());
            lines.append(&mut func.lines);
        }

        for line in lines {
            writeln!(wr, "{}", line.as_string())?;
        }

        Ok(())
    }
}

